import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import Script from 'next/script';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  
<html lang="en-US">

{/* <!-- Mirrored from html.ditsolution.net/dreamit/handyman/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 20 Nov 2024 18:34:09 GMT --> */}
<head>
	<meta charSet="UTF-8"/>
	<meta httpEquiv="x-ua-compatible" content="ie=edge"/>
	<title>MEP Services</title>
	<meta name="description" content=""/>
	<meta name="viewport" content="width=device-width, initial-scale=1"/>
	{/* <!-- Favicon --> */}
	<link rel="icon" type="image/png" sizes="56x56" href="assets/images/fav-icon/icon.png"/>
	{/* <!-- bootstrap CSS --> */}
	<link rel="stylesheet" href="assets/css/bootstrap.min.css" type="text/css" media="all" />
	{/* <!-- carousel CSS --> */}
	<link rel="stylesheet" href="assets/css/owl.carousel.min.css" type="text/css" media="all" />	
	{/* <!-- nivo-slider CSS --> */}
	<link rel="stylesheet" href="assets/css/nivo-slider.css" type="text/css" media="all" />
	{/* <!-- animate CSS --> */}
	<link rel="stylesheet" href="assets/css/animate.css" type="text/css" media="all" />	
	{/* <!-- animated-text CSS --> */}
	<link rel="stylesheet" href="assets/css/animated-text.css" type="text/css" media="all" />	
	{/* <!-- font-awesome CSS --> */}
	<link rel="stylesheet" href="assets/css/all.min.css" type="text/css" media="all" />	
	{/* <!-- font-flaticon CSS --> */}
	<link rel="stylesheet" href="assets/css/flaticon.css" type="text/css" media="all" />	
	{/* <!-- theme-default CSS --> */}
	<link rel="stylesheet" href="assets/css/theme-default.css" type="text/css" media="all" />	
	{/* <!-- meanmenu CSS --> */}
	<link rel="stylesheet" href="assets/css/meanmenu.min.css" type="text/css" media="all" />	
	{/* <!-- Main Style CSS --> */}
	<link rel="stylesheet"  href="style.css" type="text/css" media="all" />
	{/* <!-- transitions CSS --> */}
	<link rel="stylesheet" href="assets/css/owl.transitions.css" type="text/css" media="all" />
	{/* <!-- venobox CSS --> */}
	<link rel="stylesheet" href="venobox/venobox.css" type="text/css" media="all" />
	{/* <!-- widget CSS --> */}
	<link rel="stylesheet" href="assets/css/widget.css" type="text/css" media="all" />
	{/* <!-- responsive CSS --> */}
	<link rel="stylesheet" href="assets/css/responsive.css" type="text/css" media="all" />
	{/* <!-- modernizr js -->	 */}

	<link rel="stylesheet" type="text/css" href="assets/css/slick.css"/>
  <link rel="stylesheet" type="text/css" href="assets/css/slick-theme.css"/>
	
</head>

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

	{/* <!-- Loder --> */}
	<div className="loader-wrapper">
	  <div className="loader"></div>
	  <div className="loder-section left-section"></div>
	  <div className="loder-section right-section"></div>
	</div>
	{/* <!-- Loder End --> */}
{/* <!--==================================================-->
<!-- Start	Militant Header Top Menu Area -->
<!--==================================================-->	 */}
<div className="header-top-area">
	<div className="container">
		<div className="row">
			<div className="col-md-8 col-lg-8">
				<div className="dreamit-header-menu-address">
					<ul>
						<li><Link href="#"><i className="far fa-envelope"></i> info@example.com</Link></li>
						<li><span><i className="fas fa-map-marker-alt"></i> 1st Floor New World.</span></li>
						<li><Link href="#"><i className="fas fa-phone"></i> +880 320 432 242</Link></li>
					</ul>
				</div>
			</div>
			<div className="col-md-4 col-lg-4">
				<div className="dreamit-header-top-socail">
					<Link href="#"><i className="fab fa-facebook-f"></i></Link>
					<Link href="#"><i className="fa-brands fa-x-twitter"></i></Link>
					<Link href="#"><i className="fab fa-linkedin-in"></i></Link>
					<Link href="#"><i className="fab fa-pinterest-p"></i></Link>
				</div>
			</div>
		</div>
	</div>
</div>
{/* <!--==================================================-->
<!-- End	Militant Header  Area -->
<!--==================================================-->

<!--==================================================-->
<!-- Start dreamit Main Menu Area -->
<!--==================================================--> */}
<div id="sticky-header" className="dreamit_nav_manu">
	<div className="container">
		<div className="row align-items-center">
			<div className="col-lg-3">
				<div className="logo">
					<Link className="logo_img" href="/" title="dreamit">
						<img src="/assets/images/data-tech-logo.png" alt="" />
					</Link>
					<Link className="main_sticky" href="/" title="dreamit">
						<img src="/assets/images/data-tech-logo.png" alt="astute" />
					</Link>
				</div>
			</div>
			<div className="col-lg-9">
			
				<nav className="dreamit_menu">
					<ul className="nav_scroll">
						
						
						<li><Link href="/">Home</Link></li>
						
						<li><Link href="/about-us">About</Link></li>
						
						
						<li><Link href="">Services <span><i className="fas fa-angle-down"></i></span></Link>
							<ul className="sub-menu">
								<li><Link href="/service/electrical-repairs-and-maintenance-dubai">Electrical Repairs & Maintenance Dubai</Link></li>
								<li><Link href="/service/electrical-installations">Electrical Installations</Link></li>
								<li><Link href="/service/emergency-electrician">Emergency Electrician (24/7 Service)</Link></li>
								<li><Link href="/service/residential-electrical-services">Residential Electrical Services</Link></li>
                                <li><Link href="/service/wiring-and-rewiring-services">Wiring & Rewiring Services</Link></li>
								<li><Link href="/service/commercial-and-industrial-electrical-services">Commercial & Industrial Electrical Services</Link></li>
							</ul>
						</li>
						
						<li><Link href="/blogs">Blogs</Link></li>
						
						<li><Link href="/contact-us">Contact</Link></li>
					</ul>
					<div className="header-button">
						<Link className="dtbtn" href="/">Get A Quote</Link>	
					</div>	
					
				</nav>
				
			</div>
		</div>
	</div>
</div>
{/* <!-- dreamit Mobile Menu Area --> */}
{/* <div className="mobile-menu-area d-sm-block d-md-block d-lg-none ">
	<div className="mobile-menu">
		<nav className="dreamit_menu">
			<ul className="nav_scroll">
				
				<li><Link href="/">Home</Link></li>
				
				<li><Link href="/company">About</Link></li>
				
				<li><Link href="/portfolio">Services <span><i className="fas fa-angle-down"></i></span></Link>
					<ul className="sub-menu">
						<li><Link href="#">Electrical Service</Link></li>
						<li><Link href="#">Plumbing Service</Link></li>
						<li><Link href="#">Mechanical Service</Link></li>
					</ul>
				</li>
				
				<li><Link href="blog-grid.html">Blogs</Link></li>
				
				
				<li><Link href="/contact">Contact</Link></li>

			</ul>
		</nav>
	</div>
</div> */}
        {children}
{/*       
  <!--==================================================-->
<!-- Start dreamit Footer Middle Area -->
<!--==================================================--> */}

<div className="footer-middle style_two pt-80 pb-3"> 
	<div className="container">
		<div className="row">
			<div className="col-lg-3 col-md-6 col-sm-12">
				<div className="widget widgets-company-info">
					<div className="dreamit-logo">
						<Link className="logo_img" href="/" title="dreamit">
							<img src="/assets/images/logo.png" alt="" />
						</Link>
					</div>
					<div className="company-info-desc pr-2">
						<p>Sedut perspiciatis unde omnis iste natus error sitlutem acc usantium doloremque</p>
					</div>
					<div className="company_icon">
						<Link className="facebook" href="#"><i className="fab fa-facebook-f"></i></Link>
						<Link className="instagram" href="#"><i className="fab fa-instagram"></i></Link>
						<Link className="pinterest" href="#"><i className="fab fa-pinterest-p"></i></Link>
						<Link className="twitter" href="#"><i className="fa-brands fa-x-twitter"></i></Link>
					</div>
				</div>					
			</div>
			<div className="col-lg-3 col-md-6 col-sm-12">
				<div className="widget widget-nav-menu pl-2">
					<h4 className="widget-title">Our Service</h4>
					<div className="menu-quick-link-content">
						<ul className="menu">
							<li><Link href="/services-detail">Our Services</Link></li>
							<li><Link href="#">Electrician Services</Link></li>
							<li><Link href="#">Handyman Service</Link></li>
							<li><Link href="#">Plumbing Services</Link></li>
							<li><Link href="#">Repair Services</Link></li>
						</ul>
					</div>
				</div>
			</div>	
			<div className="col-lg-3 col-md-6 col-sm-12">
				<div className="widget-footer-title">
					<h2>Recent Post</h2>
				</div>
				<div className="footer-recent-post style-two">
					<div className="footer-recent-post-thumb">
						<Link href="#"><img src="/assets/images/resource/footer.jpg" alt=""/></Link>
					</div>
					<div className="footer-recent-post-title">
						<h4><Link href="#">Plumbing Tips For Winter and summer</Link></h4>
						<span>10 July, 2024</span>
					</div>
				</div>
				<div className="footer-recent-post">
					<div className="footer-recent-post-thumb">
						<Link href="#"><img src="/assets/images/resource/footer2.jpg" alt=""/></Link>
					</div>
					<div className="footer-recent-post-title">
						<h4><Link href="#">Equipping Researchers in the Developing.</Link></h4>
						<span>10 July, 2024</span>
					</div>
				</div>
			</div>
			<div className="col-lg-3 col-md-6 col-sm-12">
				<div id="footer-widget-address">
					<div className="footer-widget-address-inner">
						<h4 className="widget-title">Quick Contact</h4>
						<div className="footer-inner pr-2">
							<div className="footer-socail-icon">
								<i className="fa fa-home"></i>
							</div>
							<div className="footer-socail-info">
								<p>
									<span>Address:</span>
									<br/>Dhaka, Bangladesh Road 22
								</p>
							</div>
						</div>
						<div className="footer-inner pr-2">
							<div className="footer-socail-icon">
								<i className="fa fa-phone"></i>
							</div>
							<div className="footer-socail-info">
								<p>
									<span>Teliphone:</span>
									<br/>088 4785 6589
								</p>
							</div>
						</div>
						<div className="footer-inner pr-2">
							<div className="footer-socail-icon">
								<i className="fa fa-globe"></i>
							</div>
							<div className="footer-socail-info">
								<p>
									<span>Email:</span>
									<br/>info@example.com
								</p>
							</div>
						</div>
					</div>
				</div>	
			</div>
		</div>
		<div className="row footer-bottom mt-50">
			<div className="col-lg-6 col-md-6">
				<div className="footer-bottom-content">
					<div className="footer-bottom-content-copy">
						<p>Copyright © dreamit all rights reserved.</p>
					</div>
				</div>
			</div>
			<div className="col-lg-6">
			</div>
		</div>
	</div>
</div>		
{/* <!--==================================================-->
<!-- End dreamit Footer Middle Area -->
<!--==================================================-->

<!--==================================================-->
<!-- Start scrollup section Area -->
<!--==================================================-->
<!-- scrollup section --> */}

<div className="scroll-area">
	<div className="top-wrap">
		<div className="go-top-btn-wraper">
			<div className="go-top go-top-button">
				<i className="fas fa-arrow-up"></i>
				<i className="fas fa-arrow-up"></i>
			</div>
		</div>
	</div>
</div>
{/* <!--==================================================-->
<!-- Start scrollup section Area -->
<!--==================================================-->

<!--==================================================-->
<!-- Start Search Popup Area -->
<!--==================================================--> */}

<div className="search-popup">
	<button className="close-search style-two"><span className="flaticon-multiply"></span></button>
	<button className="close-search"><span className="flaticon-up-arrow-1"></span></button>
	<form method="post" action="#">
		<div className="form-group">
			<input type="search" name="search-field" value="" placeholder="Search Here" required=""/> 
			<button type="submit"><i className="fa fa-search"></i></button>
		</div>
	</form>
</div>
{/* <!--==================================================-->
<!-- Start Search Popup Area -->
<!--==================================================-->
	 */}
	{/* <!-- jquery js -->	 */}
	<Script src="assets/js/vendor/jquery-3.2.1.min.js"/>
	{/* <!-- bootstrap js -->	 */}
	<Script src="assets/js/bootstrap.min.js"/>
	{/* <!-- carousel js --> */}
	<Script src="assets/js/owl.carousel.min.js"/>
	{/* <!-- counterup js --> */}
	<Script src="assets/js/jquery.counterup.min.js"/>
	{/* <!-- waypoints js --> */}
	<Script src="assets/js/waypoints.min.js"/>
	{/* <!-- wow js --> */}
	<Script src="assets/js/wow.js"/>
	{/* <!-- imagesloaded js --> */}
	<Script src="assets/js/imagesloaded.pkgd.min.js"/>
	{/* <!-- venobox js --> */}
	<Script src="venobox/venobox.js"/>
	{/* <!-- ajax mail js --> */}
	<Script src="assets/js/ajax-mail.js"/>
	{/* <!--  animated-text js -->	 */}
	<Script src="assets/js/animated-text.js"/>
	{/* <!-- venobox min js --> */}
	<Script src="venobox/venobox.min.js"/>
	{/* <!-- isotope js --> */}
	<Script src="assets/js/isotope.pkgd.min.js"/>
	{/* <!-- jquery nivo slider pack js --> */}
	<Script src="assets/js/jquery.nivo.slider.pack.js"/>
	{/* <!-- jquery meanmenu js -->	 */}
	<Script src="assets/js/jquery.meanmenu.js"/>
	<Script src="assets/js/popper.min.js"/>
	{/* <!-- jquery revolation js -->	 */}
	<Script src="assets/js/rs6.min.js"/>
	<Script src="assets/js/rbtools.min.js"/>
	{/* <!-- jquery scrollup js -->	 */}
	<Script src="assets/js/jquery.scrollUp.js"/>
	{/* <!-- theme js -->	 */}
	<Script src="assets/js/theme.js"/>
	{/* <!-- jquery js -->
	<!-- theme js -->	 */}
	<Script src="assets/js/jquery.barfiller.js" />

  <Script src="assets/js/vendor/modernizr-3.5.0.min.js" />

	<script>
            $(document).ready(function(){`
            $('#bar1').barfiller({ duration: 7000 });
            $('#bar2').barfiller({ duration: 7000 });
            $('#bar3').barfiller({ duration: 7000 });
            `});
        </script>
</body>

{/* <!-- Mirrored from html.ditsolution.net/dreamit/handyman/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 20 Nov 2024 18:34:31 GMT --> */}
</html>
  );
}
